### ISSUE TITLE
winsocket debug client show nothing after main.lua start in quik

### ISSUE THREAD

**Issue by slukin1** [Arseniys1/QuikSocketTransfer#1]
winsocket debug client show nothing after main.lua start in quik

**Comment by Arseniys1** [comment]
Вы должны отправить:
```json
 {
  "id": 1,
  "method": "checkSecurity",
  "args": ["1"]
}
```
Чтобы проверить security ключ, после успешной проверки вам будут отправляться колбэки

**Comment by slukin1** [comment]
Tried to send {"id": 1,"method": "checkSecurity", "args": ["1"]} with telsocket, Chrome addons: Web socket client, Simple web socket client,  with python websocket client - connection established, but no response
###test_quik_websocket.py###
`from websocket import create_connection
ws = create_connection("ws://127.0.0.1:1111/")
print("Sending 'Hello, World'...")
ws.send({"id": 1,"method": "checkSecurity","args": ["1"]})
print("Sent")
print("Receiving...")
result =  ws.recv()
print("Received '%s'" % result)
ws.close()`

**Comment by slukin1** [comment]
Got solution. Winsocket  not equal to Websocket
# -*- coding: utf-8 -*-
import socket
import json
sock = socket.socket()
sock.connect(('127.0.0.1', 1111))
sock.send(json.dumps({"id": "1","method": "checkSecurity","args": ["1"]}).encode())
data = sock.recv(1024)
print(data)
sock.close()

**Comment by slukin1** [comment]
if sending not one param_name - response empty
sock.send(json.dumps({"id": "3", "method": "getInfoParam","args": ["VERSION"]}).encode())
response ok 'message:{"id":"3","result":["7.18.1.20"]}'
sock.send(json.dumps({"id": "3", "method": "getInfoParam","args": ["VERSION","TRADEDATE"]}).encode())
response empty 'message:{"id":"3","result":[]}'

**Comment by Arseniys1** [comment]
Забыл еще сказать что сообщения нужно отправлять так: "message:{"id": 1,"method": "checkSecurity","args": ["1"]}"

**Comment by Arseniys1** [comment]
`import socket
import json

sock = socket.socket()
sock.connect(('localhost', 1111))
mes = json.dumps({
	'id': 1,
	'method': 'checkSecurity',
	'args': ['1'],
})
sock.send(("message:" + mes).encode("windows-1251"))

mes = json.dumps({
	'id': 1,
	'method': 'CreateDataSource',
	'args': ["SPBFUT", "SiU8", "INTERVAL_TICK"],
})
sock.send(("message:" + mes).encode("windows-1251"))

mes = json.dumps({
	'id': 1,
	'method': 'SetUpdateCallback',
	'args': [1],
})
sock.send(("message:" + mes).encode("windows-1251"))

mes = json.dumps({
	'id': 1,
	'method': 'Close',
	'args': [1],
})
sock.send(("message:" + mes).encode("windows-1251"))

while True:
	data = sock.recv(1024)
	data = data.decode("utf-8")
	if data is "":
		break
	print(data)


# mes = json.dumps({
# 	'id': 1,
# 	'method': 'getInfoParam',
# 	'args': ['IPADDRESS'],
# })
# sock.send(("message:" + mes).encode("windows-1251"))

# data = sock.recv(1024)
# print(data)
# data = sock.recv(1024)
# print(data)

sock.close()
`

**Comment by Arseniys1** [comment]
Вот ссылка как работает getInfoParam http://luaq.ru/getInfoParam.html
Он принимает только 1 аргумент param_name

**Comment by slukin1** [comment]
Correct method to receive callback continuously?
buffer = ''
sock.send(("message:" + mes).encode("windows-1251"))
while True:
    data = sock.recv(1024)
    if data:
        buffer += str(data)
        print(buffer)
    else:
        break

**Comment by Arseniys1** [comment]
```python
while True:
	messages = sock.recv(1024).decode("utf-8")
	if messages is "":
		sock.close()
		break

	messages = messages.split("message:")

	for message in messages:
		if message is "":
			continue
		print("New message: " + message)
```

**Comment by Arseniys1** [comment]
Скорость я не сравнивал. trans2quik не нужен.

**Comment by slukin1** [comment]
Great work! Time to test
